# Generated by Django 2.2.5 on 2020-02-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelbeseiten', '0002_gelbeseitencompany_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelbeseitencompany',
            name='city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
