# Generated by Django 2.2.5 on 2020-02-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelbeseiten', '0003_gelbeseitencompany_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GelbeSeitenCompany',
            new_name='Entry',
        ),
        migrations.RenameModel(
            old_name='ScrapeRun',
            new_name='Fetch',
        ),
    ]
