# Generated by Django 2.2.5 on 2020-02-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelbeseiten', '0004_auto_20200205_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapefile',
            name='tool',
        ),
    ]
