# Generated by Django 2.2.5 on 2020-02-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelbeseiten', '0006_remove_fetch_tool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapeFile',
            new_name='File',
        ),
    ]
