# Generated by Django 2.2.5 on 2020-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtvClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('members', models.SmallIntegerField(blank=True, null=True)),
                ('adult_members', models.SmallIntegerField(blank=True, null=True)),
                ('youth_members', models.SmallIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('outside_courts', models.SmallIntegerField(blank=True, null=True)),
                ('indoor_courts', models.SmallIntegerField(blank=True, null=True)),
                ('competition_courts', models.SmallIntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GelbeSeitenCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media/fpioli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.CharField(choices=[('BTV', 'BTV Tool'), ('GS', 'Gelbe Seiten Tool')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.CharField(choices=[('BTV', 'BTV Tool'), ('GS', 'Gelbe Seiten Tool')], max_length=20)),
            ],
        ),
    ]
