# Generated by Django 2.2.5 on 2020-02-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpioli', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GelbeSeitenCompany',
        ),
    ]
