# Generated by Django 2.2.5 on 2020-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Url')),
                ('location', models.CharField(choices=[('HEAD', 'Head'), ('BODY', 'Body')], help_text='Where is the code supposed to be?', max_length=200, verbose_name='Location')),
                ('code', models.TextField(help_text='The code is not validated and should be correct.', verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Code',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(help_text='How the page shows up in the url.', unique=True, verbose_name='Slug')),
                ('shown_in_footer_other', models.BooleanField(help_text='Should a link to the page in the footer be displayed?', verbose_name='Shown in the footer section other')),
                ('shown_in_footer_legal', models.BooleanField(help_text='Should a link to the page in the footer be displayed?', verbose_name='Shown in the footer section legal')),
                ('shown_in_navigation', models.BooleanField(help_text='Should a link to the page in the navigation be displayed?', verbose_name='Shown in the navigation')),
                ('html_activated', models.BooleanField(help_text='Should the content be rendered as html?', verbose_name='Html Code Activated')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, help_text='Activates on this url. If empty usually active.', max_length=200, unique=True, verbose_name='Url')),
                ('title_tag', models.CharField(max_length=200, verbose_name='Title')),
                ('meta_description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Seo Setting',
                'verbose_name_plural': 'Seo Settings',
            },
        ),
    ]
